#!/usr/bin/env node
/* build-de-data.mjs — generate roadmap-data-de.js (window.FUEL_*_DE).
 *
 * German twin of build-th-data.mjs. Clones the EN data structures and overlays
 * German text (from scripts/de-translations.json) by id, keeping every
 * structural field intact. Only structures with at least one translation are
 * emitted — the rest fall back to EN in the app (getDeData: FUEL_*_DE ||
 * FUEL_*_EN). Untranslated items inside an emitted structure keep their EN text
 * (per-item fallback).
 *
 * Terminology is fixed by scripts/de-glossary.md (owner-approved decisions:
 * procurement=Einkauf, stockout=Out-of-Stock, loss control=Verlustkontrolle,
 * pump price=Säulenpreis, working capital=Working Capital, AI=KI, Sie-form).
 *
 * Re-run after editing de-translations.json:  node scripts/build-de-data.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const win = {};
new Function('window', readFileSync(join(root, 'existing/roadmap-data.js'), 'utf8'))(win);
const TR = JSON.parse(readFileSync(join(here, 'de-translations.json'), 'utf8'));

const overlayArray = (enArr, trMap) =>
  enArr.map((item) => (trMap[item.id] ? { ...item, ...trMap[item.id] } : { ...item }));
const overlayObj = (enObj, trMap) => {
  const out = {};
  for (const k of Object.keys(enObj)) out[k] = trMap[k] ? { ...enObj[k], ...trMap[k] } : { ...enObj[k] };
  return out;
};
const hasAny = (o) => o && Object.keys(o).length > 0;

/* --- id sanity check: a translation id with no match in the EN data would fall
 * back to English silently (the b-logistics-supply / b-logistics bug from the
 * Thai pass). Fail loudly instead. --------------------------------------- */
// NB: ids are compared as strings — FUEL_STAGES_EN uses numeric ids (1/2/3),
// while JSON object keys are always strings.
const idsOf = (arr) => new Set(arr.map((i) => String(i.id)));
const CHECKS = [
  ['stages', TR.stages, idsOf(win.FUEL_STAGES_EN)],
  ['blocks', TR.blocks, idsOf(win.FUEL_BLOCKS_EN)],
  ['subblocks', TR.subblocks, idsOf(win.FUEL_SUBBLOCKS_EN)],
  ['problems', TR.problems, idsOf(win.FUEL_PROBLEMS_EN)],
  ['cards', TR.cards, idsOf(win.FUEL_CARDS_EN)],
  ['drawer', TR.drawer, new Set(Object.keys(win.FUEL_DRAWER_CONTENT_EN || {}))],
];
let orphans = 0;
for (const [name, tr, ids] of CHECKS) {
  if (!hasAny(tr)) continue;
  for (const id of Object.keys(tr)) {
    if (!ids.has(id)) { console.error(`  !! ${name}: unknown id "${id}" — no match in EN data`); orphans++; }
  }
  const missing = [...ids].filter((id) => !tr[id]);
  if (missing.length) console.error(`  .. ${name}: ${missing.length} EN item(s) not translated → EN fallback: ${missing.join(', ')}`);
}
if (orphans) {
  console.error(`\nABORT: ${orphans} unmatched id(s) in de-translations.json. Fix them — they fail silently at runtime.`);
  process.exit(1);
}
console.error('  id check: OK (0 unmatched ids)\n');

const parts = [];
const emit = (name, value, count) => {
  parts.push(`window.${name} = ${JSON.stringify(value)};`);
  console.error(`  ${name}: ${count} translated`);
};

if (hasAny(TR.stages))    emit('FUEL_STAGES_DE',    overlayArray(win.FUEL_STAGES_EN,    TR.stages),    Object.keys(TR.stages).length);
if (hasAny(TR.blocks))    emit('FUEL_BLOCKS_DE',    overlayArray(win.FUEL_BLOCKS_EN,    TR.blocks),    Object.keys(TR.blocks).length);
if (hasAny(TR.subblocks)) emit('FUEL_SUBBLOCKS_DE', overlayArray(win.FUEL_SUBBLOCKS_EN, TR.subblocks), Object.keys(TR.subblocks).length);
if (hasAny(TR.problems))  emit('FUEL_PROBLEMS_DE',  overlayArray(win.FUEL_PROBLEMS_EN,  TR.problems),  Object.keys(TR.problems).length);
// Fixed impact/scale tag values (a 7-value set) — translated in place so the
// card pills render German. Their style is a neutral fallback regardless of the
// value, so translating them here is safe.
const CARD_TAG_DE = {
  'Quick Win': 'Quick Win', 'Scoped Project': 'Abgegrenztes Projekt', 'Major Program': 'Großprogramm',
  'Productivity': 'Produktivität', 'Cost reduction': 'Kostensenkung', 'Decision quality': 'Entscheidungsqualität', 'Revenue growth': 'Umsatzwachstum',
};
const deTag = (v) => (typeof v === 'string' && CARD_TAG_DE[v]) || v;
if (hasAny(TR.cards)) {
  const cardsDE = overlayArray(win.FUEL_CARDS_EN, TR.cards).map(c => ({
    ...c,
    scale: deTag(c.scale),
    impact: Array.isArray(c.impact) ? c.impact.map(deTag) : deTag(c.impact),
  }));
  emit('FUEL_CARDS_DE', cardsDE, Object.keys(TR.cards).length);
}
if (hasAny(TR.drawer))    emit('FUEL_DRAWER_CONTENT_DE', overlayObj(win.FUEL_DRAWER_CONTENT_EN, TR.drawer), Object.keys(TR.drawer).length);

const banner = '/* AUTO-GENERATED by scripts/build-de-data.mjs — do not edit by hand. Edit de-translations.json + re-run. German first pass, pending native review. */\n';
writeFileSync(join(root, 'existing/roadmap-data-de.js'), banner + parts.join('\n') + '\n');
console.error(`roadmap-data-de.js written (${parts.length} structures).`);
