#!/usr/bin/env node
/* build-th-data.mjs — generate roadmap-data-th.js (window.FUEL_*_TH).
 *
 * Clones the EN data structures and overlays Thai text (from
 * scripts/th-translations.json) by id, keeping every structural field intact.
 * Only structures with at least one translation are emitted — the rest fall
 * back to EN in the app (getThData: FUEL_*_TH || FUEL_*_EN). Untranslated items
 * inside an emitted structure keep their EN text (per-item fallback).
 *
 * Re-run after editing th-translations.json:  node scripts/build-th-data.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const win = {};
new Function('window', readFileSync(join(root, 'existing/roadmap-data.js'), 'utf8'))(win);
const TR = JSON.parse(readFileSync(join(here, 'th-translations.json'), 'utf8'));

const overlayArray = (enArr, trMap) =>
  enArr.map((item) => (trMap[item.id] ? { ...item, ...trMap[item.id] } : { ...item }));
const overlayObj = (enObj, trMap) => {
  const out = {};
  for (const k of Object.keys(enObj)) out[k] = trMap[k] ? { ...enObj[k], ...trMap[k] } : { ...enObj[k] };
  return out;
};
const hasAny = (o) => o && Object.keys(o).length > 0;

const parts = [];
const emit = (name, value, count) => {
  parts.push(`window.${name} = ${JSON.stringify(value)};`);
  console.error(`  ${name}: ${count} translated`);
};

if (hasAny(TR.stages))    emit('FUEL_STAGES_TH',    overlayArray(win.FUEL_STAGES_EN,    TR.stages),    Object.keys(TR.stages).length);
if (hasAny(TR.blocks))    emit('FUEL_BLOCKS_TH',    overlayArray(win.FUEL_BLOCKS_EN,    TR.blocks),    Object.keys(TR.blocks).length);
if (hasAny(TR.subblocks)) emit('FUEL_SUBBLOCKS_TH', overlayArray(win.FUEL_SUBBLOCKS_EN, TR.subblocks), Object.keys(TR.subblocks).length);
if (hasAny(TR.problems))  emit('FUEL_PROBLEMS_TH',  overlayArray(win.FUEL_PROBLEMS_EN,  TR.problems),  Object.keys(TR.problems).length);
// Fixed impact/scale tag values (a 7-value set) — translated in place so the
// card pills render Thai. Their style is a neutral fallback regardless of the
// value, so translating them here is safe.
const CARD_TAG_TH = {
  'Quick Win': 'ชนะเร็ว', 'Scoped Project': 'โครงการที่กำหนดขอบเขต', 'Major Program': 'โปรแกรมใหญ่',
  'Productivity': 'ผลิตภาพ', 'Cost reduction': 'การลดต้นทุน', 'Decision quality': 'คุณภาพการตัดสินใจ', 'Revenue growth': 'การเติบโตของรายได้',
};
const thTag = (v) => (typeof v === 'string' && CARD_TAG_TH[v]) || v;
if (hasAny(TR.cards)) {
  const cardsTH = overlayArray(win.FUEL_CARDS_EN, TR.cards).map(c => ({
    ...c,
    scale: thTag(c.scale),
    impact: Array.isArray(c.impact) ? c.impact.map(thTag) : thTag(c.impact),
  }));
  emit('FUEL_CARDS_TH', cardsTH, Object.keys(TR.cards).length);
}
if (hasAny(TR.drawer))    emit('FUEL_DRAWER_CONTENT_TH', overlayObj(win.FUEL_DRAWER_CONTENT_EN, TR.drawer), Object.keys(TR.drawer).length);

const banner = '/* AUTO-GENERATED by scripts/build-th-data.mjs — do not edit by hand. Edit th-translations.json + re-run. Thai first pass, pending native review. */\n';
writeFileSync(join(root, 'existing/roadmap-data-th.js'), banner + parts.join('\n') + '\n');
console.error(`roadmap-data-th.js written (${parts.length} structures).`);
